[build]
  command = "cd client && npm install && npm run build && cd .. && npm install"
  publish = "client/build"

[functions]
  external_node_modules = true
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"